pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/gitea
        tags: [1.8.1, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
