pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: dashie/gitea
        tags: [1.9.1, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
